### PR TITLE
Wing file cleanup (#188)

### PR DESCRIPTION
**Pull request by ivanwills**
Cleaning up the wing files

### CODE REVIEW

**Comment by nathf** [comment]
The markup examples are auto generated, why are they now added manually in the README?

**Comment by ivanwills** [comment]
@nathf are they really? There is no current way to show example hbs usage only data driven examples (Unless #174 gets approved). Also it's there to encourage people to actually write some documentation as in most cases there is not documentation to speak of.

**Comment by ScottMaclure** [comment]
I'm not a fan of maintaining markup examples. Ill look at #174 soon

**Comment by ivanwills** [comment]
What about markup tests? We should be able to test plain markup does what is intended.

**Comment by ivanwills** [comment]
HTML examples are now removed, should have no objections now

**Pull request merged**
