### PR TITLE
Generating docs

### PR DESCRIPTION
**Pull request by pvshum**
Refactoring documentation generator task

### CODE REVIEW

**Comment by nathf** [comment]
@pvshum Conflicts to resolve!

**Comment by nathf** [comment]
@pvshum @ScottMaclure can we merge this one or are we waiting for @steven-bruce-au's changes?

**Comment by ScottMaclure** [comment]
I think @pvshum actively working on this

**Comment by pvshum** [comment]
Hey guys, I've done a dry run merging this branch into master on my local, everything seems to be working fine.
Please have a look and approve if happy.

@nathf @ScottMaclure

**Pull request merged**
